### ISSUE TITLE
Zorin OS 17 (Linux Ubuntu Based)

### ISSUE THREAD

**Issue by pablo-hp** [KRTirtho/flemozi#35] opened 2024-02-18 04:02 UTC
Two problems. 
1 - The shortcuts configuration is not working. 
2 - When opening the application, it becomes completely transparent, that is, nothing appears, but it shows that it is open in the taskbar. With some insistence, constantly opening and closing the application, sometimes it opens normally and visibly.

It's an application that I would like to have on my Linux, but it isn't working.

**Comment by lumbric** [comment] 2024-03-26 09:32
Oh I just noticed, (1) is a duplicate of #37. (2) is a duplicate of #4.

**Closed** 2024-09-27 17:51 UTC
